<?php
$config = array(
'title' => '24Hours.Host - Надёжный игровой хостинг провайдер для вашего сервера.',
'description' => '24Hours.Host - Хостинг игровых серверов с Защитой от DoS/DDoS Атак, по оптимальным ценам и профессиональной службой поддержки.',
'keywords' => 'Аренда серверов, игровой хостинг,24Hours.Host, www.24Hours.Host, 24Hours.Host, веб хостинг, аренда игровых серверов, игровой сервер с защитой от DDoS, хостинг ragemp, gta Underground, хостинг samp, хостинг crmp, автоустановка samp, хостинг mta, хостинг MineCraft, бесплатный хостинг, bighost, doome.org, swag-host, gg-host, хостинг GTA 5, бесплатный хостинг самп, samp, crmp, крмп, хостинг игровых серверов, crmp хостинг, samp хостинг, mta хостинг, minecraft хостинг, ragemp хостинг, лучший игровой хостинг, дешевый, стабильный, надежный, качественный, порт, fastdl, аренда игровых серверов, хостинг игровых серверов, игровой хостинг, дешевый хостинг игровых серверов, хостинг игровых серверов css, самый дешевый хостинг игровых серверов, качественный хостинг игровых серверов, бесплатный игровой хостинг, хостинг самп,хостинг крмп,хостинг мта,самп,samp хостинг,игровой хостинг,samp mobile,crmp mobile, 24hourshost, 24hourshost.ru, 24hh.ru, 24hh.tk, 24hhru, 24hhtk',
'url' => 'https://cp.24hours.host/',
'token'			=>		'm4j6onN1tfEtPyA5nNVKi03r',								//CRON Токен,
'db_type'		=>		'mysql',										//ТИП Базы Данных,
'db_hostname'	=>		'localhost', 									//Хост: 127.0.0.1,
'db_username'	=>		'alex', 						//User: system_administrator,
'db_password' => 		'zoxe6RpM2rJvH5P7',							       				 //Password: ,
'db_database'	=>		'24hh',							//DataBase: 24HoursHost_database,
'mail_sender' => '24HoursHost Automatic Sustem',
'mail_from' => 'no-reply@24hours.host',
'mail_from1' => 'no-reply@24hours.host',                                //Почта - 2 Регистрация,
'mail_from2' => 'no-reply@24hours.host',                                    //Почта - 3 Уведомления,
'phone' => '',
'public' => '24Hours.Host',
//'logo' => '/ru/img/finxgames-logo.png',
'logo' => 'https://cp.24hours.host/assets/image/logo.svg',
'webhost' => '1',
'unitpay' => '0',
'enotpay' => '0',
'anypay' => '0',
'litekassa' => '1',
'robokassa' => '0',
'freekassa' => '1',
'interkassa' => '0',
'yandexkassa' => '0',
'qiwi' => '1',
//----------------------------------------------------------------------//UnitPay,
'unitpay_url' => '',
'unitpay_secret' => '',
//----------------------------------------------------------------------//EnotPay,
'enot_server' => 'https://enot.io/pay',
'enot_login' => '',
'enot_password1' => '',
'enot_password2' => '',
//----------------------------------------------------------------------//AnyPay,
'anypay_server'	=>	'https://anypay.io/merchant',
'anypay_login' => '',
'anypay_password' => '',
//----------------------------------------------------------------------//LiteKassa,
'lk_server'	=>	'https://www.lite-kassa.ru/pay',
'lk_login' => '',
'lk_password' => '',
//----------------------------------------------------------------------//RoboKassa,
'rk_server'		=>	'https://auth.robokassa.ru/Merchant',
'rk_login' => '',
'rk_password1' => '',
'rk_password2' => '',
//----------------------------------------------------------------------//FreeKassa,
'fk_server'		=>	'https://www.free-kassa.ru/merchant/cash.php',
'fk_login' => '',
'fk_password1' => '',
'fk_password2' => '',
//----------------------------------------------------------------------//InterKassa,
'ik_secretkey' => '',
'ik_shopid' => '',
//----------------------------------------------------------------------//YandexKassa,
'yk_login' => '',
'yk_password1' => '',
//----------------------------------------------------------------------//Qiwi,
'qiwipublickey' => '',
'qiwisecretkey' => '',
'qiwi_theme' => '0',
'qiwi_themecode' => '',
//----------------------------------------------------------------------//Авторизация VK,
'vk_id' => '51791636',
'vk_stat' => '1',
//----------------------------------------------------------------------//,
'serv_test' => '0',
'serv_free' => '1',														//Бесплатный тариф,
//----------------------------------------------------------------------//,
'offline' => '0',
'offline_res' => 'Вне плановые технические работы в Панели Управления. Технические работы будут окончены в 15:30 по Московскому Времени! ',
//----------------------------------------------------------------------//,
'recaptcha' => '6LdRWFgdAAAAAECAbNwelagnj6_2AyN6CJbHwAD9',  			//ReCaptcha Ключ HTML,
'secret_recaptcha' => '6LdRWFgdAAAAAAgl8Lvh6Un-SNyVQtRFXi4wy3il',		//ReCaptcha Секретный Ключ,
//----------------------------------------------------------------------//Бот VK,
'VK_bot' => '0',
'VK_confirmationToken' => '41355434',
'VK_token' => 'vk1.a.KYgtqzLa1fwQ3psmNHX6RVU7dWAj8pUs3KkuXBN8JHeoIoGyzGSDNMIJnFMn4H85NdcbQhphAQmcY_KpBSy5wHnuwRO7hh-2bXWkyiNFUO6N6wk4ganM8jm1qYO2y1b7zVRT1hhp7AGhNFpXe9ZPanLRxflN2yC-VpOI1g-2j87R_er-hnp1Cl3p5tbryqx4jWH4EQQlwX8aZtwNIcV1Yw',
'VK_secretKey' => 'eoMNj1TT4aybOQoQrLCf1IsiR2513GYr',
//----------------------------------------------------------------------//,
'portPrice' => '99',
'register' => '0',
'oplata_status' => '1',
'oplatahostinpl' => 'freepay',
'bonus1' => '10',
'bonus2' => '30',
'bonus3' => '60',
'bonus4' => '100',
'status_hostinpl' => '0',
'close' => 'off',
'ref_percent' => '5',
'bonus_percent' => '15',
//----------------------------------------------------------------------//
);
?>